sudo: required
services:
    - docker

before_install:
    - docker build -t vasudhak/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true vasudhak/docker-react npm run test -- --coverage